name: ci-pos-devops-atv2-node
on: 
  pull_request:
    branches:
      - master
jobs:
  check-application:
    runs-on: ubuntu-latest
    name: Testes unitários
    strategy:
      matrix:
        node-version: [20.x]    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  scan:  
    runs-on: ubuntu-latest
    name: Testes de vulnerabilidade
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          
  cypress-run:
      runs-on: ubuntu-latest
      name: Testes e2e
      strategy:
        fail-fast: false
        matrix:
          containers: [1]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Cypress run
          uses: cypress-io/github-action@v5
          with:
            start: npm start
            wait-on: 'http://localhost:3000'
            record: true
            parallel: true
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.CYPRESS_GITHUB_TOKEN }}
            
  build:
    runs-on: ubuntu-latest
    name: Scan da imagem docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t vitorbarth/pos-devops-atv2-node .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vitorbarth/pos-devops-atv2-node'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build_image:
    runs-on: ubuntu-latest
    name: Compila e publica imagem docker
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vitorbarth/pos-devops-atv2-node:latest

  

    